### ISSUE TITLE
Song Rating automatically assigns 1 star to unrated songs

### ISSUE THREAD

**Issue by edjusted** [MainasuK/Song-Rating#15]
If an unrated song plays beyond the 30 second mark, Song Rating automatically gives it a 1-star rating.

This doesn't always happen, but once it does, I can reproduce it even after quitting and restarting Song Rating.

e.g. if it's not happening, it won't happen.

I know it sounds strange. e.g. I'll have song rating running, and it works as expected (songs are only rated if I manually rate them).

But then sometimes, I'll notice that it's auto-rating songs. And if I quit and restart, it'll continue the behavior.

I *think* the problem persists until a reboot. But I don't know what's actually triggering it.

How do I stop this?

**Comment by MainasuK** [comment]
That’s weird. Could you provide the app version and OS version? Also does any other iTunes related software installed? I did fix a NepTunes bug cause a rating issue. 

And you can open the "Console.app". In the filter type "Song Rating". The app will print the logs maybe useful.

**Comment by edjusted** [comment]
I'm running Mac OS 11.2 Big Sur and Song Rating is 1.2.4 (9). The only other Music-app related software is probably SwiftBar's "Music Control Play/Pause" menu bar.

I did some more testing, and though I can't replicate it on-demand, I think it might (maybe) be related to some sort of caching/delay where I change a song to 1-star via the Song Rating menu bar and/or hot key, and then immediately switch to another song before Song Rating has a chance to set the rating. But then I was also able to replicate it with different combinations of something like:

1. Set a no-rating song to 1 or 2 stars via Song Rating
2. Immediately switch to a different song
3. Song Rating will then rate the *new* song with 1 or 2-stars
4. But then I'll manually set the new song back to no-stars in Music (not via Song Rating)
5. and *sometimes*, maybe 30-50 seconds later, *something* (Song Rating?) will set the new song back to 1 or 2 stars.

And sometimes, I'll notice that Song Rating's menu bar won't reflect the currently-playing song's rating for a long time (sometimes a few seconds, sometimes minutes).

Attached is a console
[song rating log.txt](https://github.com/MainasuK/Song-Rating/files/5940489/song.rating.log.txt)
 log. FWIW, I noticed "spontaneous" song rating changes around these times, +/- a few seconds:
12:23:50
12:25:49
12:30:50
before 12:34:20 (I was looking at another window then noticed the song rating changed, so it might've been maybe 1-20 seconds prior)

**Comment by MainasuK** [comment]
Sorry for the long waiting.

The rating will be committed to iTunes with n seconds. The rating will be set to the next song when the player switches before commit. That's could be fixed.  Currently, You could update to the latest version of Song Rating and check if the issue still happening or not. 

Also, The track star rating is different from the album rating. iTunes change the album rating logic from some version and some app use the guessed rating from the album average rating which iTunes gives. 

 I will observe the 1 or 2-star rating issue.

**Comment by edjusted** [comment]
I was finally able to track the problem down to something else.
