### ISSUE TITLE
Launching Song rating forces Music app to start as well

### ISSUE THREAD

**Issue by VKondakoff** [MainasuK/Song-Rating#7]
Recently I discovered, that Music app is suddenly launching at system startup. It turns out, that it happened because I added Song rating to the list of the apps that are launching on login.
Tested this out: every time you start Song rating Music app is silently starting as well (the dot appears under Music app icon in the dock). This is reproducible on Catalina (19A602).

Can this be fixed?

Thank you!

**Comment by MainasuK** [comment]
Verified this issue. Maybe dig out it later.

Needs read some documents about Apple Event Permission Grant.

**Comment by MainasuK** [comment]
Fixed in 1.2.1 (6)
